export const env = {
  region: process.env.AWS_REGION ?? "eu-west-1",
  accountId: process.env.ACCOUNT_ID ?? "",
  tableName: process.env.TABLE_NAME ?? "eduboost",
  userPoolId: process.env.COGNITO_USER_POOL_ID ?? "",
  userPoolClientId: process.env.COGNITO_USER_POOL_CLIENT_ID ?? "",
  uploadsBucket: process.env.UPLOADS_BUCKET ?? "",
  recordingsBucket: process.env.RECORDINGS_BUCKET ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET ?? "",
  reminderLambdaArn: process.env.REMINDER_LAMBDA_ARN ?? "",
  schedulerRoleArn: process.env.SCHEDULER_ROLE_ARN ?? "",
  scheduleGroupName: process.env.SCHEDULE_GROUP_NAME ?? "default",
  stripeStudentPremiumPriceId: process.env.STRIPE_STUDENT_PREMIUM_PRICE_ID ?? "",
  stripeTeacherProPriceId: process.env.STRIPE_TEACHER_PRO_PRICE_ID ?? "",
  webBaseUrl: process.env.WEB_BASE_URL ?? "https://eduboost.com",
  googleClientId: process.env.GOOGLE_CLIENT_ID ?? "",
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET ?? "",
  googleRedirectUrl: process.env.GOOGLE_REDIRECT_URL ?? "",
  googleStateSecret: process.env.GOOGLE_STATE_SECRET ?? "",
  bedrockGradingModelId: process.env.BEDROCK_GRADING_MODEL_ID ?? "",
};
